name: Deploy
on: 
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        env:
          CLONE_DIR: /home/john/front-grp4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: CLONE_DIR
          port: 22
          script: |
            echo "Hello world $CLONE_DIR"
            echo git@github.com:${{github.repository}}.git
            rm -rf $CLONE_DIR
            git clone -b feature/add-deploy-workflow git@github.com:${{github.repository}}.git $CLONE_DIR
            cd $CLONE_DIR
            npm install
            npm run build